# Generated by Django 5.2.17 on 2026-10-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_task_updated_at_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', to='kanban.task'),
        ),
    ]
